version: 2

updates:
    - package-ecosystem: "npm"
      directory: "/functions/functions"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "⬆️"
          include: "scope"
