language: node_js
node_js:
    - node
    - lts/*
os:
    - linux
    - osx
    - windows
install:
    - cd functions/functions
    - yarn install --ignore-engines
script:
    - yarn --ignore-engines build
