language: node_js
node_js:
    - node
    - lts/*
os:
    - linux
    - osx

before_install:
    - npm i -g yarn

install:
    - cd functions/functions
    - yarn install --ignore-engines
script:
    - yarn --ignore-engines build
