language: node_js
node_js:
    - node
    - lts/*
os:
    - linux
    - osx
    - windows

before_install:
    - npm i -g yarn

install:
    - cd functions/functions
    - yarn install --ignore-engines
    - cd ../../client
    - yarn install

script:
    - cd ../functions/functions && yarn --ignore-engines build
    - cd ../../client && yarn build
