name: Lint

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    run-linters:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            # ESLint and Prettier must be in `package.json`
            - name: Install dependencies
              run: cd functions/functions && yarn install

            - name: Run linters
              uses: wearerequired/lint-action@v1
              with:
                  eslint: true
                  eslint_dir: functions/functions/
                  eslint_extensions: ts
