name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x, 15.x, 16.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Function Dependencies
              run: cd functions/functions && yarn --ignore-engines install

            - name: Build Functions
              run: cd functions/functions && yarn --ignore-engines build

            - name: Install Client Dependencies
              run: cd client && yarn install

            - name: Build Client
              run: cd client && yarn build
