name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x, 15.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v1

            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: cd functions/functions && yarn install && cd ../../client && yarn install

            - name: Compile Function Typescript
            - run: cd functions/functions && yarn --ignore-engines build

            - name: Compile React App
            - run: cd client && yarn build
